### ISSUE TITLE
New service that can consume MQ queues and send emails on certain conditions.

### ISSUE THREAD

**Issue by viklund** [neicnordic/sda-pipeline#426]
This is another new service that can notify people in case things happen in the system. It should be configured to be able to listen to queues in the system and upon certain conditions send out an email to the submitter.

## Tasks:
- [ ] Create skeleton service for notify service
- [ ] Listen to the error queue and send an email to the submitter for errors
- [ ] Listen to the mq queue that gets "ready" messages and send out an email once the final ready message for a submission is recieved.

**Comment by csc-felipe** [comment]
It would be nice if this could be relatively generic. I can see a couple more use cases for us.

On a first thought, perhaps it could have a configuration system that allows to set multiple of listening queue, message template, destination email.

What do you think?

**Comment by viklund** [comment]
Yes I think genericism is good too.

Since we start with 2 separate notifications (one for errors and one for everything is complete) we have a good base to start from for figuring out how it should be generic.

I see there are at least 3 things you want to be able to configure:
 - Email template (fairly simple)
 - MQ to listen too (very simple)
 - Some criteria that should be fulfilled for an email to be sent when a message arrives in the MQ (quite difficult)


For the criteria a first step could be to just give a reference to a function that should be called to evaluate? The config could be something like (example only, might not work):

```yaml
  - template: error.template
    mq: v1.errors
    trigger_function: always
  - template: done.template
    mq: v1.ready
    trigger_function: check_all_done
```

But I suggest that step one is to just implement the two use-cases separately. And then as step 2 look at them and see if they can be abstracted and configured in some good way (for example like I suggested above, some other method might be better). Usually it's not until the second or third rewrite that these things start to work out.

**Comment by csc-felipe** [comment]
Perhaps there could be a simpler solution for implementing the trigger.
What about matching a regex? So the config file would be.

```
  - template: error.template
    mq: v1.errors
    trigger_regex: /.*/
  - template: done.template
    mq: v1.ready
    trigger_regex: /Done/
```
